### ISSUE TITLE
Better streaming server setup

### ISSUE THREAD

**Issue by hbredin** [ghostsphinx/web-evidence#4]
Would be great to have some kind of modal (http://getbootstrap.com/javascript/#modals) that appears at login time to setup the streaming server -- instead of having to do that by clicking on the checkbox in the header and setting the address...

This could also allow the annotator to check if the webpage is able to communicate with the server.
For instance, when the user enters the URL of the streaming server, it could display one video and a precomputed screenshot of the video that is expected to appear if the streaming server is working...

**Comment by ghostsphinx** [comment]
I have pushed my work on it.

**Comment by hbredin** [comment]
That's great already! You're nearly there 👍 

You can hide "Use default path:" as we will not allow the Camomile server to stream videos...

**Comment by ghostsphinx** [comment]
I remove default path from the modal, but I also remove it from all the code, since it is not used.
I manage to use cookie to "store" the path like before, previous version had lost it, but there is a process to follow, I will make it automatic or more simple later. For now, I consider this issue closed.
